name: democapstone
services:
  api:
    build:
      context: ./backend/democapstone
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=sql,1433;Database=democapstone;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;MultipleActiveResultSets=True
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://api:8080
    ports:
      - "8088:80"
    depends_on:
      - api
