version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
